// <auto-generated />
namespace beta.TheSoundOf.net.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Showsurladdedtoproducers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Showsurladdedtoproducers));
        
        string IMigrationMetadata.Id
        {
            get { return "201307171601526_Shows url added to producers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
