// <auto-generated />
namespace beta.TheSoundOf.net.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addisblocked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addisblocked));
        
        string IMigrationMetadata.Id
        {
            get { return "201307171558206_Add is blocked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
